sudo: false
language: node_js
node_js:
  - "4.4.4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
branches:
  except:
    - gh-pages
before_script:
  - npm install -g gulp@3.9.1
script:
  - npm run lint
  - npm run coverage
after_script:
  - if [[ `node --version` == *v4.4.4* ]]; then cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi
